# Generated by Django 3.2 on 2021-04-22 01:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ساخت')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='آخرین زمان تغییر')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('account_type', models.CharField(choices=[('client', 'کاربر'), ('admin', 'ادمین')], default='client', max_length=10)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تماس ')),
            ],
            options={
                'verbose_name': 'اکانت',
                'verbose_name_plural': 'اکانت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=256)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('token_expiration', models.DateTimeField(default=datetime.datetime(2021, 4, 22, 3, 17, 29, 597892))),
                ('account_type', models.CharField(choices=[('client', 'کاربر'), ('admin', 'ادمین')], default='client', max_length=10)),
            ],
        ),
    ]
